// 공항 코드 타입
export interface Airport {
  code: string;
  name: string;
}

// 전세계 주요 공항 목록
export const WORLD_MAJOR_AIRPORTS: Airport[] = [
  // 대한민국
  { code: 'ICN', name: '서울/인천 (ICN)' },
  { code: 'GMP', name: '서울/김포 (GMP)' },
  { code: 'PUS', name: '부산/김해 (PUS)' },
  { code: 'CJU', name: '제주 (CJU)' },
  { code: 'TAE', name: '대구 (TAE)' },
  { code: 'CJJ', name: '청주 (CJJ)' },
  { code: 'MWX', name: '무안 (MWX)' },

  // 일본
  { code: 'HND', name: '도쿄/하네다 (HND)' },
  { code: 'NRT', name: '도쿄/나리타 (NRT)' },
  { code: 'KIX', name: '오사카/간사이 (KIX)' },
  { code: 'ITM', name: '오사카/이타미 (ITM)' },
  { code: 'NGO', name: '나고야/중부 (NGO)' },
  { code: 'FUK', name: '후쿠오카 (FUK)' },
  { code: 'CTS', name: '삿포로/신치토세 (CTS)' },
  { code: 'OKA', name: '오키나와/나하 (OKA)' },

  // 중국, 홍콩, 마카오, 대만
  { code: 'PEK', name: '베이징/서우두 (PEK)' },
  { code: 'PKX', name: '베이징/다싱 (PKX)' },
  { code: 'PVG', name: '상하이/푸둥 (PVG)' },
  { code: 'SHA', name: '상하이/훙차오 (SHA)' },
  { code: 'CAN', name: '광저우 (CAN)' },
  { code: 'SZX', name: '선전 (SZX)' },
  { code: 'CTU', name: '청두/솽류 (CTU)' },
  { code: 'TFU', name: '청두/톈푸 (TFU)' },
  { code: 'XIY', name: '시안 (XIY)' },
  { code: 'HGH', name: '항저우 (HGH)' },
  { code: 'XMN', name: '샤먼 (XMN)' },
  { code: 'TAO', name: '칭다오 (TAO)' },
  { code: 'CKG', name: '충칭 (CKG)' },
  { code: 'KMG', name: '쿤밍 (KMG)' },
  { code: 'NKG', name: '난징 (NKG)' },
  { code: 'WUH', name: '우한 (WUH)' },
  { code: 'CSX', name: '창사 (CSX)' },
  { code: 'HKG', name: '홍콩 (HKG)' },
  { code: 'MFM', name: '마카오 (MFM)' },
  { code: 'TPE', name: '타이베이/타오위안 (TPE)' },
  { code: 'TSA', name: '타이베이/쑹산 (TSA)' },
  { code: 'KHH', name: '가오슝 (KHH)' },

  // 동남아시아
  { code: 'SIN', name: '싱가포르/창이 (SIN)' },
  { code: 'BKK', name: '방콕/수완나품 (BKK)' },
  { code: 'DMK', name: '방콕/돈므앙 (DMK)' },
  { code: 'HKT', name: '푸껫 (HKT)' },
  { code: 'CNX', name: '치앙마이 (CNX)' },
  { code: 'KUL', name: '쿠알라룸푸르 (KUL)' },
  { code: 'PEN', name: '페낭 (PEN)' },
  { code: 'JHB', name: '조호르바루 (JHB)' },
  { code: 'CGK', name: '자카르타 (CGK)' },
  { code: 'DPS', name: '발리/덴파사르 (DPS)' },
  { code: 'SUB', name: '수라바야 (SUB)' },
  { code: 'MNL', name: '마닐라 (MNL)' },
  { code: 'CEB', name: '세부 (CEB)' },
  { code: 'HAN', name: '하노이 (HAN)' },
  { code: 'SGN', name: '호치민 (SGN)' },
  { code: 'DAD', name: '다낭 (DAD)' },
  { code: 'PNH', name: '프놈펜 (PNH)' },
  { code: 'SAI', name: '씨엠립/앙코르 (SAI)' },
  { code: 'VTE', name: '비엔티안 (VTE)' },
  { code: 'RGN', name: '양곤 (RGN)' },

  // 남아시아
  { code: 'DEL', name: '델리 (DEL)' },
  { code: 'BOM', name: '뭄바이 (BOM)' },
  { code: 'BLR', name: '벵갈루루 (BLR)' },
  { code: 'MAA', name: '첸나이 (MAA)' },
  { code: 'HYD', name: '하이데라바드 (HYD)' },
  { code: 'CCU', name: '콜카타 (CCU)' },
  { code: 'AMD', name: '아마다바드 (AMD)' },
  { code: 'COK', name: '코치 (COK)' },
  { code: 'KTM', name: '카트만두 (KTM)' },
  { code: 'DAC', name: '다카 (DAC)' },
  { code: 'CMB', name: '콜롬보 (CMB)' },
  { code: 'MLE', name: '말레 (MLE)' },
  { code: 'ISB', name: '이슬라마바드 (ISB)' },
  { code: 'LHE', name: '라호르 (LHE)' },
  { code: 'KHI', name: '카라치 (KHI)' },

  // 중동, 중앙아시아, 튀르키예
  { code: 'DXB', name: '두바이 (DXB)' },
  { code: 'DWC', name: '두바이/알막툼 (DWC)' },
  { code: 'AUH', name: '아부다비 (AUH)' },
  { code: 'SHJ', name: '샤르자 (SHJ)' },
  { code: 'DOH', name: '도하 (DOH)' },
  { code: 'MCT', name: '무스카트 (MCT)' },
  { code: 'KWI', name: '쿠웨이트 (KWI)' },
  { code: 'BAH', name: '바레인 (BAH)' },
  { code: 'RUH', name: '리야드 (RUH)' },
  { code: 'JED', name: '제다 (JED)' },
  { code: 'DMM', name: '담맘 (DMM)' },
  { code: 'AMM', name: '암만 (AMM)' },
  { code: 'TLV', name: '텔아비브 (TLV)' },
  { code: 'BEY', name: '베이루트 (BEY)' },
  { code: 'IST', name: '이스탄불 (IST)' },
  { code: 'SAW', name: '이스탄불/사비하 괵첸 (SAW)' },
  { code: 'TAS', name: '타슈켄트 (TAS)' },
  { code: 'ALA', name: '알마티 (ALA)' },

  // 오세아니아
  { code: 'SYD', name: '시드니 (SYD)' },
  { code: 'MEL', name: '멜버른 (MEL)' },
  { code: 'BNE', name: '브리즈번 (BNE)' },
  { code: 'PER', name: '퍼스 (PER)' },
  { code: 'ADL', name: '애들레이드 (ADL)' },
  { code: 'OOL', name: '골드코스트 (OOL)' },
  { code: 'AKL', name: '오클랜드 (AKL)' },
  { code: 'CHC', name: '크라이스트처치 (CHC)' },
  { code: 'WLG', name: '웰링턴 (WLG)' },
  { code: 'NAN', name: '난디 (NAN)' },

  // 유럽
  { code: 'LHR', name: '런던/히스로 (LHR)' },
  { code: 'LGW', name: '런던/개트윅 (LGW)' },
  { code: 'STN', name: '런던/스탠스테드 (STN)' },
  { code: 'MAN', name: '맨체스터 (MAN)' },
  { code: 'EDI', name: '에든버러 (EDI)' },
  { code: 'DUB', name: '더블린 (DUB)' },
  { code: 'CDG', name: '파리/샤를드골 (CDG)' },
  { code: 'ORY', name: '파리/오를리 (ORY)' },
  { code: 'AMS', name: '암스테르담 (AMS)' },
  { code: 'FRA', name: '프랑크푸르트 (FRA)' },
  { code: 'MUC', name: '뮌헨 (MUC)' },
  { code: 'BER', name: '베를린 (BER)' },
  { code: 'DUS', name: '뒤셀도르프 (DUS)' },
  { code: 'HAM', name: '함부르크 (HAM)' },
  { code: 'ZRH', name: '취리히 (ZRH)' },
  { code: 'GVA', name: '제네바 (GVA)' },
  { code: 'VIE', name: '빈 (VIE)' },
  { code: 'BRU', name: '브뤼셀 (BRU)' },
  { code: 'CPH', name: '코펜하겐 (CPH)' },
  { code: 'ARN', name: '스톡홀름/알란다 (ARN)' },
  { code: 'OSL', name: '오슬로 (OSL)' },
  { code: 'HEL', name: '헬싱키 (HEL)' },
  { code: 'KEF', name: '레이캬비크 (KEF)' },
  { code: 'MAD', name: '마드리드 (MAD)' },
  { code: 'BCN', name: '바르셀로나 (BCN)' },
  { code: 'LIS', name: '리스본 (LIS)' },
  { code: 'OPO', name: '포르투 (OPO)' },
  { code: 'FCO', name: '로마/피우미치노 (FCO)' },
  { code: 'MXP', name: '밀라노/말펜사 (MXP)' },
  { code: 'VCE', name: '베네치아 (VCE)' },
  { code: 'ATH', name: '아테네 (ATH)' },
  { code: 'PRG', name: '프라하 (PRG)' },
  { code: 'BUD', name: '부다페스트 (BUD)' },
  { code: 'WAW', name: '바르샤바 (WAW)' },
  { code: 'KRK', name: '크라쿠프 (KRK)' },
  { code: 'OTP', name: '부쿠레슈티 (OTP)' },
  { code: 'SOF', name: '소피아 (SOF)' },
  { code: 'BEG', name: '베오그라드 (BEG)' },
  { code: 'ZAG', name: '자그레브 (ZAG)' },

  // 북미
  { code: 'JFK', name: '뉴욕/JFK (JFK)' },
  { code: 'EWR', name: '뉴욕/뉴어크 (EWR)' },
  { code: 'LGA', name: '뉴욕/라과디아 (LGA)' },
  { code: 'BOS', name: '보스턴 (BOS)' },
  { code: 'PHL', name: '필라델피아 (PHL)' },
  { code: 'IAD', name: '워싱턴 D.C./덜레스 (IAD)' },
  { code: 'DCA', name: '워싱턴 D.C./레이건 (DCA)' },
  { code: 'ATL', name: '애틀랜타 (ATL)' },
  { code: 'MIA', name: '마이애미 (MIA)' },
  { code: 'FLL', name: '포트로더데일 (FLL)' },
  { code: 'MCO', name: '올랜도 (MCO)' },
  { code: 'TPA', name: '탬파 (TPA)' },
  { code: 'ORD', name: '시카고/오헤어 (ORD)' },
  { code: 'MDW', name: '시카고/미드웨이 (MDW)' },
  { code: 'DFW', name: '댈러스-포트워스 (DFW)' },
  { code: 'IAH', name: '휴스턴/인터컨티넨털 (IAH)' },
  { code: 'HOU', name: '휴스턴/하비 (HOU)' },
  { code: 'DEN', name: '덴버 (DEN)' },
  { code: 'LAS', name: '라스베이거스 (LAS)' },
  { code: 'PHX', name: '피닉스 (PHX)' },
  { code: 'LAX', name: '로스앤젤레스 (LAX)' },
  { code: 'SFO', name: '샌프란시스코 (SFO)' },
  { code: 'SJC', name: '산호세 (SJC)' },
  { code: 'SEA', name: '시애틀 (SEA)' },
  { code: 'PDX', name: '포틀랜드 (PDX)' },
  { code: 'SAN', name: '샌디에이고 (SAN)' },
  { code: 'SLC', name: '솔트레이크시티 (SLC)' },
  { code: 'MSP', name: '미니애폴리스 (MSP)' },
  { code: 'DTW', name: '디트로이트 (DTW)' },
  { code: 'CLT', name: '샬럿 (CLT)' },
  { code: 'BWI', name: '볼티모어 (BWI)' },
  { code: 'HNL', name: '호놀룰루 (HNL)' },
  { code: 'YYZ', name: '토론토 (YYZ)' },
  { code: 'YVR', name: '밴쿠버 (YVR)' },
  { code: 'YUL', name: '몬트리올 (YUL)' },
  { code: 'YYC', name: '캘거리 (YYC)' },
  { code: 'YOW', name: '오타와 (YOW)' },
  { code: 'YEG', name: '에드먼턴 (YEG)' },
  { code: 'YHZ', name: '핼리팩스 (YHZ)' },
  { code: 'MEX', name: '멕시코시티 (MEX)' },
  { code: 'CUN', name: '칸쿤 (CUN)' },
  { code: 'GDL', name: '과달라하라 (GDL)' },
  { code: 'MTY', name: '몬테레이 (MTY)' },
  { code: 'SJD', name: '로스카보스 (SJD)' },

  // 카리브해, 중남미
  { code: 'HAV', name: '하바나 (HAV)' },
  { code: 'PUJ', name: '푼타카나 (PUJ)' },
  { code: 'SDQ', name: '산토도밍고 (SDQ)' },
  { code: 'SJU', name: '산후안 (SJU)' },
  { code: 'MBJ', name: '몬테고베이 (MBJ)' },
  { code: 'NAS', name: '나소 (NAS)' },
  { code: 'PTY', name: '파나마시티 (PTY)' },
  { code: 'SJO', name: '산호세/코스타리카 (SJO)' },
  { code: 'GUA', name: '과테말라시티 (GUA)' },
  { code: 'BOG', name: '보고타 (BOG)' },
  { code: 'MDE', name: '메데인 (MDE)' },
  { code: 'LIM', name: '리마 (LIM)' },
  { code: 'UIO', name: '키토 (UIO)' },
  { code: 'GYE', name: '과야킬 (GYE)' },
  { code: 'SCL', name: '산티아고 (SCL)' },
  { code: 'EZE', name: '부에노스아이레스/에세이사 (EZE)' },
  { code: 'AEP', name: '부에노스아이레스/호르헤 뉴베리 (AEP)' },
  { code: 'GRU', name: '상파울루/과룰류스 (GRU)' },
  { code: 'GIG', name: '리우데자네이루/갈레앙 (GIG)' },
  { code: 'BSB', name: '브라질리아 (BSB)' },
  { code: 'CNF', name: '벨루오리존치 (CNF)' },
  { code: 'POA', name: '포르투알레그리 (POA)' },
  { code: 'SSA', name: '살바도르 (SSA)' },
  { code: 'REC', name: '헤시피 (REC)' },
  { code: 'FOR', name: '포르탈레자 (FOR)' },
  { code: 'MVD', name: '몬테비데오 (MVD)' },
  { code: 'ASU', name: '아순시온 (ASU)' },
  { code: 'LPB', name: '라파스 (LPB)' },
  { code: 'VVI', name: '산타크루스/비루비루 (VVI)' },

  // 아프리카
  { code: 'CAI', name: '카이로 (CAI)' },
  { code: 'CMN', name: '카사블랑카 (CMN)' },
  { code: 'RAK', name: '마라케시 (RAK)' },
  { code: 'ALG', name: '알제 (ALG)' },
  { code: 'TUN', name: '튀니스 (TUN)' },
  { code: 'ADD', name: '아디스아바바 (ADD)' },
  { code: 'NBO', name: '나이로비 (NBO)' },
  { code: 'DAR', name: '다르에스살람 (DAR)' },
  { code: 'JNB', name: '요하네스버그 (JNB)' },
  { code: 'CPT', name: '케이프타운 (CPT)' },
  { code: 'DUR', name: '더반 (DUR)' },
  { code: 'LOS', name: '라고스 (LOS)' },
  { code: 'ABV', name: '아부자 (ABV)' },
  { code: 'ACC', name: '아크라 (ACC)' },
  { code: 'DKR', name: '다카르 (DKR)' },
  { code: 'ABJ', name: '아비장 (ABJ)' },
  { code: 'KGL', name: '키갈리 (KGL)' },
  { code: 'EBB', name: '엔테베 (EBB)' },
  { code: 'MRU', name: '모리셔스 (MRU)' },
  { code: 'SEZ', name: '세이셸 (SEZ)' },
];

// 출발지 공항 목록
export const ORIGIN_AIRPORTS: Airport[] = WORLD_MAJOR_AIRPORTS;

// 도착지 공항 목록
export const ARRIVAL_AIRPORTS: Airport[] = WORLD_MAJOR_AIRPORTS;
